version: 2

configs:
  - &job_config
    docker:
      - image: circleci/android:api-28-alpha
    working_directory: ~/repo
    environment:
      _JAVA_OPTIONS: "-Xmx2048m -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap"
      GRADLE_OPTS: '-Dorg.gradle.jvmargs="-Xmx2048m" -Dorg.gradle.daemon=false'

reusable-steps:
  - &restore_cache
    restore_cache:
      keys:
      - v1-dependencies-{{ checksum "dependencies.gradle" }}
      # fallback to using the latest cache if no exact match is found
      - v1-dependencies-
  - &save_cache
    save_cache:
      paths:
        - ~/.gradle
        - ~/.android
      key: v1-dependencies-{{ checksum "dependencies.gradle" }}
  - &setup_aws_cli
    run:
      name: Setup AWS CLI
      command: sudo pip install awscli
  - &gradle_props
    run:
      name: Write gradle.properties
      command: /bin/bash writegradleprops.sh
  - &download_android_deps
    run:
      name: Download Android Dependencies
      command: ./gradlew androidDependencies

  - &test
    run:
      name: Test
      command: ./gradlew clean test
  - &build
    run:
      name: Build and copy
      command: ./gradlew build

  - &publish_to_qa
    run:
      name: Publish to QA
      command: ./gradlew build
  - &publish_to_snapshot
    run:
      name: Publish to Snapshot
      command: ./gradlew build
  - &publish_to_release
    run:
      name: Publish to Release
      command: ./gradlew build javadoc bintrayUpload


experimental:
  notify:
    branches:
      only:
        - develop
        - master
        - /.*release.*/

jobs:
  build:
    <<: *job_config
    steps:
      - *setup_aws_cli
      - checkout
      - *gradle_props
      - *restore_cache
      - *download_android_deps
      - *save_cache
      - *test

  deploy-qa:
    <<: *job_config
    steps:
      - *setup_aws_cli
      - checkout
      - *gradle_props
      - *restore_cache
      - *publish_to_qa

  deploy-snapshot:
    <<: *job_config
    steps:
      - *setup_aws_cli
      - checkout
      - *gradle_props
      - *restore_cache
      - *publish_to_snapshot

  deploy-release:
    <<: *job_config
    steps:
      - *setup_aws_cli
      - checkout
      - *gradle_props
      - *restore_cache
      - *publish_to_release

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy-qa:
          requires:
            - build
          filters:
            branches:
              only: /.*release.*/
      - deploy-snapshot:
          requires:
            - build
          filters:
            branches:
              only: develop
      - deploy-release:
          requires:
            - build
          filters:
            branches:
              only: master
